# -*- coding: utf-8 -*-
"""main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EiZHQQdLOvTuKkZQKkN6INjjUnvvs0CD
"""

import math


# PROBLEMA 2: CALCULADORA GENERAL DE COMBINACIONES

def calcular_combinacion(n: int, r: int) -> int:
    if not isinstance(n, int) or not isinstance(r, int):
        raise TypeError("Los parámetros n y r deben ser enteros.")
    if n < 0 or r < 0:
        raise ValueError("Ni n ni r pueden ser negativos.")
    if r > n:
        raise ValueError("r no puede ser mayor que n.")

    if r > n // 2:
        r = n - r

    if r == 0:
        return 1

    numerador = 1
    denominador = 1
    for i in range(1, r + 1):
        numerador *= (n - r + i)
        denominador *= i
    return numerador // denominador

def verificar_simetria(n: int, r: int) -> bool:
    val1 = calcular_combinacion(n, r)
    val2 = calcular_combinacion(n, n - r)
    return val1 == val2

def generar_fila_pascal(n: int) -> list:
    if n < 0:
        raise ValueError("La fila debe ser un entero no negativo.")
    fila = [1]
    actual = 1
    for i in range(n):
        actual = actual * (n - i) // (i + 1)
        fila.append(actual)
    return fila


# PROBLEMA 3: CONTEO DE CADENAS BINARIAS CON RESTRICCIONES

def contar_cadenas_binarias(n: int, restriccion: str, k: int = 0) -> int:
    if not isinstance(n, int) or n < 0:
        raise ValueError("La longitud n debe ser un entero no negativo.")

    if restriccion == "todas":
        return 2**n

    elif restriccion == "exactamente":
        if k < 0 or k > n: return 0
        return calcular_combinacion(n, k)

    elif restriccion == "a_lo_sumo":
        if k < 0: return 0
        k = min(k, n)
        return sum(calcular_combinacion(n, i) for i in range(k + 1))

    elif restriccion == "al_menos":
        if k > n: return 0
        k = max(0, k)
        return sum(calcular_combinacion(n, i) for i in range(k, n + 1))

    elif restriccion == "iguales":
        if n % 2 != 0:
            return 0
        return calcular_combinacion(n, n // 2)

    else:
        raise ValueError("Restricción no reconocida.")


# EJECUCIÓN DE PRUEBAS DEL PROBLEMA 2 Y EL PROBLEMA 3

if __name__ == "__main__":
    print("=== PRUEBAS PROBLEMA 2: COMBINACIONES ===")
    print(f"Prueba 1 (Estándar): C(6, 3) = {calcular_combinacion(6, 3)}")
    print(f"Prueba 2 (Caso r=0): C(10, 0) = {calcular_combinacion(10, 0)}")
    print(f"Prueba 3 (Verificar Simetría): C(8, 3) == C(8, 5) -> {verificar_simetria(8, 3)}")
    print(f"Prueba 4 (Fila Pascal n=4): {generar_fila_pascal(4)}")
    print(f"Prueba 5 (Fila Pascal n=6): {generar_fila_pascal(6)}")

    print("\n=== PRUEBAS PROBLEMA 3: CADENAS BINARIAS ===")
    print(f"Prueba 1 (Todas las cadenas n=5): {contar_cadenas_binarias(5, 'todas')}")
    print(f"Prueba 2 (Exactamente k=2 unos, n=4): {contar_cadenas_binarias(4, 'exactamente', 2)}")
    print(f"Prueba 3 (A lo sumo k=2 unos, n=4): {contar_cadenas_binarias(4, 'a_lo_sumo', 2)}")
    print(f"Prueba 4 (Al menos k=1 uno, n=3): {contar_cadenas_binarias(3, 'al_menos', 1)}")
    print(f"Prueba 5 (Igual número ceros y unos, n=6): {contar_cadenas_binarias(6, 'iguales')}")